# Generated by Django 5.1.4 on 2025-09-27 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CIBILScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_score', models.IntegerField(help_text='Calculated CIBIL score (300-900)')),
                ('score_range', models.CharField(choices=[('EXCELLENT', 'Excellent (750-900)'), ('GOOD', 'Good (650-749)'), ('FAIR', 'Fair (550-649)'), ('POOR', 'Poor (300-549)')], max_length=20)),
                ('payment_history_score', models.FloatField(help_text='Payment history component (35% weight)')),
                ('credit_utilization_score', models.FloatField(help_text='Credit utilization component (30% weight)')),
                ('credit_history_length_score', models.FloatField(help_text='Credit history length component (15% weight)')),
                ('credit_mix_score', models.FloatField(help_text='Credit mix component (10% weight)')),
                ('new_credit_score', models.FloatField(help_text='New credit inquiries component (10% weight)')),
                ('payment_history_percentage', models.FloatField(default=0.0, help_text='% of on-time payments')),
                ('average_credit_utilization', models.FloatField(default=0.0, help_text='Average credit utilization %')),
                ('credit_history_months', models.IntegerField(default=0, help_text='Length of credit history in months')),
                ('total_credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('late_payments_count', models.IntegerField(default=0)),
                ('missed_payments_count', models.IntegerField(default=0)),
                ('overlimit_instances', models.IntegerField(default=0)),
                ('high_utilization_months', models.IntegerField(default=0)),
                ('improvement_suggestions', models.JSONField(default=list, help_text='AI-generated improvement suggestions')),
                ('risk_factors', models.JSONField(default=list, help_text='Identified risk factors')),
                ('positive_factors', models.JSONField(default=list, help_text='Positive factors helping score')),
                ('calculation_date', models.DateTimeField(auto_now_add=True)),
                ('data_source_period_start', models.DateField(blank=True, null=True)),
                ('data_source_period_end', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cibil_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-calculation_date'],
            },
        ),
        migrations.CreateModel(
            name='ScoreFactorImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_type', models.CharField(choices=[('PAYMENT_HISTORY', 'Payment History'), ('CREDIT_UTILIZATION', 'Credit Utilization'), ('CREDIT_LENGTH', 'Credit History Length'), ('CREDIT_MIX', 'Credit Mix'), ('NEW_CREDIT', 'New Credit'), ('LATE_PAYMENT', 'Late Payment'), ('MISSED_PAYMENT', 'Missed Payment'), ('HIGH_UTILIZATION', 'High Utilization'), ('OVERLIMIT', 'Over Limit'), ('CREDIT_LIMIT_INCREASE', 'Credit Limit Increase')], max_length=30)),
                ('factor_description', models.TextField()),
                ('impact_level', models.CharField(choices=[('VERY_POSITIVE', 'Very Positive (+50 to +100)'), ('POSITIVE', 'Positive (+20 to +49)'), ('SLIGHTLY_POSITIVE', 'Slightly Positive (+5 to +19)'), ('NEUTRAL', 'Neutral (0)'), ('SLIGHTLY_NEGATIVE', 'Slightly Negative (-5 to -19)'), ('NEGATIVE', 'Negative (-20 to -49)'), ('VERY_NEGATIVE', 'Very Negative (-50 to -100)')], max_length=20)),
                ('impact_points', models.IntegerField(help_text='Point impact on score (-100 to +100)')),
                ('current_value', models.FloatField(blank=True, help_text='Current value of the factor', null=True)),
                ('recommended_value', models.FloatField(blank=True, help_text='Recommended value for improvement', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cibil_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factor_impacts', to='cibil.cibilscore')),
            ],
            options={
                'ordering': ['-impact_points'],
            },
        ),
        migrations.CreateModel(
            name='ScoreSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_name', models.CharField(max_length=255)),
                ('base_score', models.IntegerField(help_text='Starting score for simulation')),
                ('proposed_changes', models.JSONField(help_text='JSON of proposed changes')),
                ('projected_score', models.IntegerField(help_text='Projected score after changes')),
                ('score_improvement', models.IntegerField(help_text='Expected score improvement')),
                ('timeframe_months', models.IntegerField(help_text='Expected timeframe for improvement')),
                ('implementation_difficulty', models.CharField(choices=[('EASY', 'Easy (0-3 months)'), ('MODERATE', 'Moderate (3-6 months)'), ('DIFFICULT', 'Difficult (6-12 months)'), ('VERY_DIFFICULT', 'Very Difficult (12+ months)')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_simulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score_improvement', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditHealthTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('average_utilization', models.FloatField(default=0.0)),
                ('total_spending', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('on_time_payments', models.IntegerField(default=0)),
                ('late_payments', models.IntegerField(default=0)),
                ('missed_payments', models.IntegerField(default=0)),
                ('total_fees_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_interest_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_score_change', models.IntegerField(default=0, help_text='Estimated score change for this month')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_trends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'month', 'year')},
            },
        ),
    ]
