# Generated by Django 4.2.7 on 2025-09-27 13:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('annual_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('preferred_tax_regime', models.CharField(choices=[('OLD', 'Old Regime'), ('NEW', 'New Regime')], default='NEW', max_length=10)),
                ('financial_year', models.CharField(default='2024-25', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('INVESTMENT', 'Investment'), ('OTHER', 'Other')], max_length=20)),
                ('ai_category', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_confidence_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_tax_relevant', models.BooleanField(default=False)),
                ('tax_section', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by_ai', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaxCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=7)),
                ('gross_total_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('old_regime_total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('new_regime_total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recommended_regime', models.CharField(choices=[('OLD', 'Old'), ('NEW', 'New')], max_length=10)),
                ('tax_savings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('calculation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'financial_year')},
            },
        ),
    ]
