# Generated by Django 5.2.6 on 2025-09-27 18:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_optimization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('BANK_STATEMENT', 'Bank Statement'), ('SALARY_SLIP', 'Salary Slip'), ('FORM_16', 'Form 16'), ('INVESTMENT_PROOF', 'Investment Proof'), ('INSURANCE_PREMIUM', 'Insurance Premium Receipt'), ('OTHER', 'Other Document')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='documents/%Y/%m/')),
                ('file_size', models.BigIntegerField()),
                ('processing_status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIALLY_PROCESSED', 'Partially Processed')], default='UPLOADED', max_length=20)),
                ('processing_message', models.TextField(blank=True, null=True)),
                ('transactions_extracted', models.IntegerField(default=0)),
                ('ai_processed', models.BooleanField(default=False)),
                ('ai_processing_time', models.FloatField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_type', models.CharField(choices=[('PPF', 'Public Provident Fund'), ('EPF', 'Employee Provident Fund'), ('ELSS', 'Equity Linked Savings Scheme'), ('NSC', 'National Savings Certificate'), ('TAX_SAVER_FD', 'Tax Saver Fixed Deposit'), ('LIFE_INSURANCE', 'Life Insurance Premium'), ('HEALTH_INSURANCE', 'Health Insurance Premium'), ('HOME_LOAN', 'Home Loan Principal'), ('EDUCATION_LOAN', 'Education Loan Interest'), ('NPS', 'National Pension System'), ('OTHER', 'Other Investments')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('investment_date', models.DateField()),
                ('financial_year', models.CharField(max_length=7)),
                ('tax_section', models.CharField(max_length=10)),
                ('eligible_deduction', models.DecimalField(decimal_places=2, max_digits=12)),
                ('institution_name', models.CharField(blank=True, max_length=100, null=True)),
                ('policy_number', models.CharField(blank=True, max_length=50, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxOptimizationRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('INVESTMENT', 'Investment Recommendation'), ('DEDUCTION', 'Deduction Opportunity'), ('REGIME_SWITCH', 'Tax Regime Switch'), ('TIMING', 'Transaction Timing'), ('RESTRUCTURE', 'Income Restructuring')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('potential_savings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investment_required', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('roi_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('priority', models.CharField(choices=[('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], max_length=10)),
                ('tax_section', models.CharField(blank=True, max_length=10, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('ai_model_version', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', '-potential_savings', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime', models.CharField(choices=[('OLD', 'Old Tax Regime'), ('NEW', 'New Tax Regime')], max_length=10)),
                ('financial_year', models.CharField(max_length=7)),
                ('min_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('section_name', models.CharField(blank=True, max_length=10, null=True)),
                ('deduction_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='financialtransaction',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='taxcalculation',
            options={'ordering': ['-calculation_date']},
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='ai_subcategory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='is_deductible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='is_manually_categorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='manual_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='business_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='capital_gains',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='new_regime_cess',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='new_regime_tax_liability',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='new_regime_taxable_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='old_regime_cess',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='old_regime_tax_liability',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='old_regime_taxable_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='other_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='salary_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='section_80c_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='section_80d_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='standard_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('INVESTMENT', 'Investment'), ('TRANSFER', 'Transfer'), ('EMI', 'EMI Payment'), ('INSURANCE', 'Insurance Premium'), ('TAX', 'Tax Payment'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='AIModelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('task_type', models.CharField(max_length=50)),
                ('accuracy', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('precision', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('recall', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('f1_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('avg_processing_time', models.FloatField()),
                ('total_predictions', models.IntegerField()),
                ('successful_predictions', models.IntegerField()),
                ('measurement_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('model_name', 'model_version', 'measurement_date')},
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings Account'), ('CURRENT', 'Current Account'), ('SALARY', 'Salary Account')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tax_optimization.bankaccount'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['user', 'date'], name='tax_optimiz_user_id_ba91b8_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['transaction_type', 'is_tax_relevant'], name='tax_optimiz_transac_4beae1_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['ai_category', 'ai_confidence_score'], name='tax_optimiz_ai_cate_cd4651_idx'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxoptimizationrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='taxrule',
            unique_together={('regime', 'financial_year', 'min_income', 'section_name')},
        ),
    ]
