# Generated by Django 5.2.6 on 2025-09-27 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_optimization', '0002_creditaccount_creditimprovementrecommendation_and_more'),
        ('tax_optimization', '0002_fileupload_investment_taxoptimizationrecommendation_and_more'),
    ]

    operations = [
    ]
