# Generated by Django 5.1.4 on 2025-09-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_optimization', '0003_merge_20250928_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcalculation',
            name='is_automatic',
            field=models.BooleanField(default=False),
        ),
    ]
