# Generated by Django 5.2.6 on 2025-09-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
