# Generated by Django 5.2.6 on 2025-09-27 20:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_analyzer', '0002_uploadedpdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='auto_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedpdf',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV')], default='pdf', max_length=10),
        ),
        migrations.AddField(
            model_name='uploadedpdf',
            name='filename',
            field=models.CharField(default='unnamed.pdf', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedpdf',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadedpdf',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(default='Uncategorized', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_analyzer.uploadedpdf')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
